SET IDENTITY_INSERT [dbo].[Modelo] ON
INSERT INTO [dbo].[Modelo] ([Id], [Nombre], [Marca], [Descripcion]) VALUES (1, N'A4 1994-2000', 1, NULL)
INSERT INTO [dbo].[Modelo] ([Id], [Nombre], [Marca], [Descripcion]) VALUES (2, N'A4 2002-2004', 1, NULL)
INSERT INTO [dbo].[Modelo] ([Id], [Nombre], [Marca], [Descripcion]) VALUES (4, N'A4 2004-2008', 1, NULL)
INSERT INTO [dbo].[Modelo] ([Id], [Nombre], [Marca], [Descripcion]) VALUES (5, N'A4 2011-2012', 1, NULL)
INSERT INTO [dbo].[Modelo] ([Id], [Nombre], [Marca], [Descripcion]) VALUES (6, N'A4 2013-2014', 1, NULL)
INSERT INTO [dbo].[Modelo] ([Id], [Nombre], [Marca], [Descripcion]) VALUES (7, N'A6 2005-2008', 1, NULL)
INSERT INTO [dbo].[Modelo] ([Id], [Nombre], [Marca], [Descripcion]) VALUES (8, N'A6 2005-2011', 1, NULL)
INSERT INTO [dbo].[Modelo] ([Id], [Nombre], [Marca], [Descripcion]) VALUES (9, N'A6 2011-2014', 1, NULL)
INSERT INTO [dbo].[Modelo] ([Id], [Nombre], [Marca], [Descripcion]) VALUES (10, N'Altea', 2, NULL)
INSERT INTO [dbo].[Modelo] ([Id], [Nombre], [Marca], [Descripcion]) VALUES (11, N'Córdoba', 2, NULL)
INSERT INTO [dbo].[Modelo] ([Id], [Nombre], [Marca], [Descripcion]) VALUES (12, N'Ibiza', 2, NULL)
INSERT INTO [dbo].[Modelo] ([Id], [Nombre], [Marca], [Descripcion]) VALUES (13, N'León', 2, NULL)
INSERT INTO [dbo].[Modelo] ([Id], [Nombre], [Marca], [Descripcion]) VALUES (14, N'Toledo', 2, NULL)
INSERT INTO [dbo].[Modelo] ([Id], [Nombre], [Marca], [Descripcion]) VALUES (15, N'Fabia Hatchback 2000-2004', 3, NULL)
INSERT INTO [dbo].[Modelo] ([Id], [Nombre], [Marca], [Descripcion]) VALUES (17, N'Fabia Hatchback 2005-2007', 3, NULL)
INSERT INTO [dbo].[Modelo] ([Id], [Nombre], [Marca], [Descripcion]) VALUES (18, N'Fabia Combi 2000-2004', 3, NULL)
INSERT INTO [dbo].[Modelo] ([Id], [Nombre], [Marca], [Descripcion]) VALUES (19, N'Fabia Combi 2005-2007', 3, NULL)
INSERT INTO [dbo].[Modelo] ([Id], [Nombre], [Marca], [Descripcion]) VALUES (20, N'Fabia Berlina 2000-2004', 3, NULL)
INSERT INTO [dbo].[Modelo] ([Id], [Nombre], [Marca], [Descripcion]) VALUES (21, N'Fabia Berlina 2005-2007', 3, NULL)
INSERT INTO [dbo].[Modelo] ([Id], [Nombre], [Marca], [Descripcion]) VALUES (22, N'Octavia Sedán 2004-2009', 3, NULL)
INSERT INTO [dbo].[Modelo] ([Id], [Nombre], [Marca], [Descripcion]) VALUES (23, N'POLO 2001-2005', 4, NULL)
INSERT INTO [dbo].[Modelo] ([Id], [Nombre], [Marca], [Descripcion]) VALUES (24, N'POLO 2005-2007', 4, NULL)
INSERT INTO [dbo].[Modelo] ([Id], [Nombre], [Marca], [Descripcion]) VALUES (25, N'POLO 2008-2009', 4, NULL)
INSERT INTO [dbo].[Modelo] ([Id], [Nombre], [Marca], [Descripcion]) VALUES (26, N'Passat 1996-2000', 4, NULL)
INSERT INTO [dbo].[Modelo] ([Id], [Nombre], [Marca], [Descripcion]) VALUES (27, N'Passat 1997-2000', 4, NULL)
INSERT INTO [dbo].[Modelo] ([Id], [Nombre], [Marca], [Descripcion]) VALUES (28, N'Passat 2000-2005', 4, NULL)
INSERT INTO [dbo].[Modelo] ([Id], [Nombre], [Marca], [Descripcion]) VALUES (29, N'Passat 2005-2010', 4, NULL)
INSERT INTO [dbo].[Modelo] ([Id], [Nombre], [Marca], [Descripcion]) VALUES (30, N'Passat 2010-2014', 4, NULL)
INSERT INTO [dbo].[Modelo] ([Id], [Nombre], [Marca], [Descripcion]) VALUES (31, N'Tourant 2003-2009', 4, NULL)
INSERT INTO [dbo].[Modelo] ([Id], [Nombre], [Marca], [Descripcion]) VALUES (32, N'Altea XL', 2, NULL)
SET IDENTITY_INSERT [dbo].[Modelo] OFF
