SET IDENTITY_INSERT [dbo].[Coche] ON
INSERT INTO [dbo].[Coche] ([Id], [Marca], [Modelo], [Motor], [Caja], [Carroceria], [Foto], [Description]) VALUES (1, 1, 1, 1, N'Manual de 5 velocidades', N'B5', NULL, NULL)
INSERT INTO [dbo].[Coche] ([Id], [Marca], [Modelo], [Motor], [Caja], [Carroceria], [Foto], [Description]) VALUES (2, 1, 2, 2, N'Manual de 5 velocidades', N'B6', NULL, NULL)
INSERT INTO [dbo].[Coche] ([Id], [Marca], [Modelo], [Motor], [Caja], [Carroceria], [Foto], [Description]) VALUES (3, 1, 2, 3, N'Manual de 5 velocidades', N'B6', NULL, NULL)
INSERT INTO [dbo].[Coche] ([Id], [Marca], [Modelo], [Motor], [Caja], [Carroceria], [Foto], [Description]) VALUES (4, 1, 2, 3, N'Multitronic', N'B6', NULL, NULL)
INSERT INTO [dbo].[Coche] ([Id], [Marca], [Modelo], [Motor], [Caja], [Carroceria], [Foto], [Description]) VALUES (5, 1, 4, 2, N'Manual de 5 velocidades', N'B7', NULL, NULL)
INSERT INTO [dbo].[Coche] ([Id], [Marca], [Modelo], [Motor], [Caja], [Carroceria], [Foto], [Description]) VALUES (6, 1, 4, 3, N'Manual de 5 velocidades', N'B7', NULL, NULL)
INSERT INTO [dbo].[Coche] ([Id], [Marca], [Modelo], [Motor], [Caja], [Carroceria], [Foto], [Description]) VALUES (7, 1, 4, 3, N'Multitronic', N'B7', NULL, NULL)
INSERT INTO [dbo].[Coche] ([Id], [Marca], [Modelo], [Motor], [Caja], [Carroceria], [Foto], [Description]) VALUES (8, 1, 5, 4, N'Multitronic', N'B8', NULL, NULL)
INSERT INTO [dbo].[Coche] ([Id], [Marca], [Modelo], [Motor], [Caja], [Carroceria], [Foto], [Description]) VALUES (9, 1, 6, 5, N'Multitronic', N'B8', NULL, NULL)
INSERT INTO [dbo].[Coche] ([Id], [Marca], [Modelo], [Motor], [Caja], [Carroceria], [Foto], [Description]) VALUES (10, 1, 7, 6, N'Multitronic', N'C6', NULL, NULL)
INSERT INTO [dbo].[Coche] ([Id], [Marca], [Modelo], [Motor], [Caja], [Carroceria], [Foto], [Description]) VALUES (11, 1, 8, 7, N'Multitronic', N'C6', NULL, NULL)
INSERT INTO [dbo].[Coche] ([Id], [Marca], [Modelo], [Motor], [Caja], [Carroceria], [Foto], [Description]) VALUES (12, 1, 9, 8, N'Multitronic', N'C7', NULL, NULL)
INSERT INTO [dbo].[Coche] ([Id], [Marca], [Modelo], [Motor], [Caja], [Carroceria], [Foto], [Description]) VALUES (14, 2, 10, 30, NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Coche] ([Id], [Marca], [Modelo], [Motor], [Caja], [Carroceria], [Foto], [Description]) VALUES (15, 2, 32, 30, NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Coche] ([Id], [Marca], [Modelo], [Motor], [Caja], [Carroceria], [Foto], [Description]) VALUES (16, 2, 11, 30, NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Coche] ([Id], [Marca], [Modelo], [Motor], [Caja], [Carroceria], [Foto], [Description]) VALUES (17, 2, 12, 30, NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Coche] ([Id], [Marca], [Modelo], [Motor], [Caja], [Carroceria], [Foto], [Description]) VALUES (18, 2, 13, 30, NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Coche] ([Id], [Marca], [Modelo], [Motor], [Caja], [Carroceria], [Foto], [Description]) VALUES (19, 2, 14, 30, NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Coche] ([Id], [Marca], [Modelo], [Motor], [Caja], [Carroceria], [Foto], [Description]) VALUES (20, 3, 15, 9, N'Manual de 5 velocidades', N'6Y2', NULL, NULL)
INSERT INTO [dbo].[Coche] ([Id], [Marca], [Modelo], [Motor], [Caja], [Carroceria], [Foto], [Description]) VALUES (21, 3, 15, 10, N'Manual de 5 velocidades', N'6Y2', NULL, NULL)
INSERT INTO [dbo].[Coche] ([Id], [Marca], [Modelo], [Motor], [Caja], [Carroceria], [Foto], [Description]) VALUES (22, 3, 17, 9, N'Manual de 5 velocidades', N'6Y2', NULL, NULL)
INSERT INTO [dbo].[Coche] ([Id], [Marca], [Modelo], [Motor], [Caja], [Carroceria], [Foto], [Description]) VALUES (23, 3, 18, 10, N'Automatica de 4 velocidades', N'6Y5', NULL, NULL)
INSERT INTO [dbo].[Coche] ([Id], [Marca], [Modelo], [Motor], [Caja], [Carroceria], [Foto], [Description]) VALUES (24, 3, 18, 10, N'Manual de 5 velocidades', N'6Y5', NULL, NULL)
INSERT INTO [dbo].[Coche] ([Id], [Marca], [Modelo], [Motor], [Caja], [Carroceria], [Foto], [Description]) VALUES (25, 3, 19, 10, N'Manual de 5 velocidades', N'6Y3', NULL, NULL)
INSERT INTO [dbo].[Coche] ([Id], [Marca], [Modelo], [Motor], [Caja], [Carroceria], [Foto], [Description]) VALUES (26, 3, 21, 10, N'Manual de 5 velocidades', N'6Y3', NULL, NULL)
INSERT INTO [dbo].[Coche] ([Id], [Marca], [Modelo], [Motor], [Caja], [Carroceria], [Foto], [Description]) VALUES (28, 3, 22, 12, N'Manual de 5 velocidades', N'1Z5', NULL, NULL)
INSERT INTO [dbo].[Coche] ([Id], [Marca], [Modelo], [Motor], [Caja], [Carroceria], [Foto], [Description]) VALUES (29, 3, 22, 13, N'Manual de 5 velocidades', N'1Z5', NULL, NULL)
INSERT INTO [dbo].[Coche] ([Id], [Marca], [Modelo], [Motor], [Caja], [Carroceria], [Foto], [Description]) VALUES (30, 3, 22, 14, N'Manual de 5 velocidades', N'1Z5', NULL, NULL)
INSERT INTO [dbo].[Coche] ([Id], [Marca], [Modelo], [Motor], [Caja], [Carroceria], [Foto], [Description]) VALUES (31, 4, 23, 10, N'Manual de 5 velocidades', N'9N', NULL, NULL)
INSERT INTO [dbo].[Coche] ([Id], [Marca], [Modelo], [Motor], [Caja], [Carroceria], [Foto], [Description]) VALUES (32, 4, 24, 16, N'Manual de 5 velocidades', N'9N3', NULL, NULL)
INSERT INTO [dbo].[Coche] ([Id], [Marca], [Modelo], [Motor], [Caja], [Carroceria], [Foto], [Description]) VALUES (33, 4, 25, 16, N'Manual de 5 velocidades', N'9N3', NULL, NULL)
INSERT INTO [dbo].[Coche] ([Id], [Marca], [Modelo], [Motor], [Caja], [Carroceria], [Foto], [Description]) VALUES (35, 4, 26, 17, N'Manual de 4 velocidades', N'B5', NULL, NULL)
INSERT INTO [dbo].[Coche] ([Id], [Marca], [Modelo], [Motor], [Caja], [Carroceria], [Foto], [Description]) VALUES (36, 4, 27, 18, N'Automatica de 5 velocidades', N'B5', NULL, NULL)
INSERT INTO [dbo].[Coche] ([Id], [Marca], [Modelo], [Motor], [Caja], [Carroceria], [Foto], [Description]) VALUES (37, 4, 27, 19, N'Automatica de 5 velocidades', N'B5', NULL, NULL)
INSERT INTO [dbo].[Coche] ([Id], [Marca], [Modelo], [Motor], [Caja], [Carroceria], [Foto], [Description]) VALUES (38, 4, 27, 19, N'Manual de 5 velocidades', N'B5', NULL, NULL)
INSERT INTO [dbo].[Coche] ([Id], [Marca], [Modelo], [Motor], [Caja], [Carroceria], [Foto], [Description]) VALUES (39, 4, 28, 20, N'Automatica de 5 velocidades', N'B5.5', NULL, NULL)
INSERT INTO [dbo].[Coche] ([Id], [Marca], [Modelo], [Motor], [Caja], [Carroceria], [Foto], [Description]) VALUES (40, 4, 28, 20, N'Manual de 5 velocidades', N'B5.5', NULL, NULL)
INSERT INTO [dbo].[Coche] ([Id], [Marca], [Modelo], [Motor], [Caja], [Carroceria], [Foto], [Description]) VALUES (42, 4, 28, 21, N'Automatica de 5 velocidades', N'B5.5', NULL, NULL)
INSERT INTO [dbo].[Coche] ([Id], [Marca], [Modelo], [Motor], [Caja], [Carroceria], [Foto], [Description]) VALUES (43, 4, 28, 21, N'Automatica de 5 velocidades', N'B5.5', NULL, NULL)
INSERT INTO [dbo].[Coche] ([Id], [Marca], [Modelo], [Motor], [Caja], [Carroceria], [Foto], [Description]) VALUES (44, 4, 29, 22, N'Manual de 6 velocidades', N'B6', NULL, NULL)
INSERT INTO [dbo].[Coche] ([Id], [Marca], [Modelo], [Motor], [Caja], [Carroceria], [Foto], [Description]) VALUES (46, 4, 29, 23, N'Automatica de 6 velocidades', N'B6', NULL, NULL)
INSERT INTO [dbo].[Coche] ([Id], [Marca], [Modelo], [Motor], [Caja], [Carroceria], [Foto], [Description]) VALUES (47, 4, 30, 24, N'Automatica de 7 velocidades', N'B7', NULL, NULL)
INSERT INTO [dbo].[Coche] ([Id], [Marca], [Modelo], [Motor], [Caja], [Carroceria], [Foto], [Description]) VALUES (48, 4, 30, 24, N'Manual de 6 velocidades', N'B7', NULL, NULL)
INSERT INTO [dbo].[Coche] ([Id], [Marca], [Modelo], [Motor], [Caja], [Carroceria], [Foto], [Description]) VALUES (49, 4, 31, 25, N'Manual de 5 velocidades', N'1T', NULL, NULL)
SET IDENTITY_INSERT [dbo].[Coche] OFF
