SET IDENTITY_INSERT [dbo].[Motor] ON
INSERT INTO [dbo].[Motor] ([Id], [Nombre], [Descripcion], [Combustible], [Capacidad], [Potencia]) VALUES (1, N'ARM', NULL, 0, 6, 101)
INSERT INTO [dbo].[Motor] ([Id], [Nombre], [Descripcion], [Combustible], [Capacidad], [Potencia]) VALUES (2, N'ALZ', NULL, 0, 6, 102)
INSERT INTO [dbo].[Motor] ([Id], [Nombre], [Descripcion], [Combustible], [Capacidad], [Potencia]) VALUES (3, N'ALT', NULL, 0, 0, 130)
INSERT INTO [dbo].[Motor] ([Id], [Nombre], [Descripcion], [Combustible], [Capacidad], [Potencia]) VALUES (4, N'CDHB', NULL, 0, 8, 160)
INSERT INTO [dbo].[Motor] ([Id], [Nombre], [Descripcion], [Combustible], [Capacidad], [Potencia]) VALUES (5, N'CJEB', NULL, 0, 8, 170)
INSERT INTO [dbo].[Motor] ([Id], [Nombre], [Descripcion], [Combustible], [Capacidad], [Potencia]) VALUES (6, N'BDW', NULL, 0, 4, 177)
INSERT INTO [dbo].[Motor] ([Id], [Nombre], [Descripcion], [Combustible], [Capacidad], [Potencia]) VALUES (7, N'BPJ', NULL, 0, 0, 170)
INSERT INTO [dbo].[Motor] ([Id], [Nombre], [Descripcion], [Combustible], [Capacidad], [Potencia]) VALUES (8, N'CDNB', NULL, 0, 0, 180)
INSERT INTO [dbo].[Motor] ([Id], [Nombre], [Descripcion], [Combustible], [Capacidad], [Potencia]) VALUES (9, N'AZQ-BME', NULL, 0, 2, 64)
INSERT INTO [dbo].[Motor] ([Id], [Nombre], [Descripcion], [Combustible], [Capacidad], [Potencia]) VALUES (10, N'BBY-BKY', NULL, 0, 4, 75)
INSERT INTO [dbo].[Motor] ([Id], [Nombre], [Descripcion], [Combustible], [Capacidad], [Potencia]) VALUES (12, N'BGU', NULL, 0, 6, 102)
INSERT INTO [dbo].[Motor] ([Id], [Nombre], [Descripcion], [Combustible], [Capacidad], [Potencia]) VALUES (13, N'BSE', NULL, 0, 6, 102)
INSERT INTO [dbo].[Motor] ([Id], [Nombre], [Descripcion], [Combustible], [Capacidad], [Potencia]) VALUES (14, N'BSF', NULL, 0, 6, 102)
INSERT INTO [dbo].[Motor] ([Id], [Nombre], [Descripcion], [Combustible], [Capacidad], [Potencia]) VALUES (16, N'BUD', NULL, 0, 4, 80)
INSERT INTO [dbo].[Motor] ([Id], [Nombre], [Descripcion], [Combustible], [Capacidad], [Potencia]) VALUES (17, N'AHU', NULL, 1, 9, 90)
INSERT INTO [dbo].[Motor] ([Id], [Nombre], [Descripcion], [Combustible], [Capacidad], [Potencia]) VALUES (18, N'AEB', NULL, 0, 8, 150)
INSERT INTO [dbo].[Motor] ([Id], [Nombre], [Descripcion], [Combustible], [Capacidad], [Potencia]) VALUES (19, N'AJM', NULL, 1, 9, 115)
INSERT INTO [dbo].[Motor] ([Id], [Nombre], [Descripcion], [Combustible], [Capacidad], [Potencia]) VALUES (20, N'AWT', NULL, 0, 8, 150)
INSERT INTO [dbo].[Motor] ([Id], [Nombre], [Descripcion], [Combustible], [Capacidad], [Potencia]) VALUES (21, N'AVF', NULL, 1, 9, 130)
INSERT INTO [dbo].[Motor] ([Id], [Nombre], [Descripcion], [Combustible], [Capacidad], [Potencia]) VALUES (22, N'BZB', NULL, 0, 8, 160)
INSERT INTO [dbo].[Motor] ([Id], [Nombre], [Descripcion], [Combustible], [Capacidad], [Potencia]) VALUES (23, N'BVZ', NULL, 0, 0, 150)
INSERT INTO [dbo].[Motor] ([Id], [Nombre], [Descripcion], [Combustible], [Capacidad], [Potencia]) VALUES (24, N'CDAA', NULL, 0, 8, 160)
INSERT INTO [dbo].[Motor] ([Id], [Nombre], [Descripcion], [Combustible], [Capacidad], [Potencia]) VALUES (25, N'BLF', NULL, 0, 6, 102)
INSERT INTO [dbo].[Motor] ([Id], [Nombre], [Descripcion], [Combustible], [Capacidad], [Potencia]) VALUES (26, N'BKD ', NULL, 1, 6, 90)
INSERT INTO [dbo].[Motor] ([Id], [Nombre], [Descripcion], [Combustible], [Capacidad], [Potencia]) VALUES (30, N'SEAT', NULL, 0, 0, 0)
SET IDENTITY_INSERT [dbo].[Motor] OFF
